[
{
	"milestone": "game_start",
	"visible": false,
	"triggers": [{"type": "game_start"}],
	"dialogs": [],
	"changes": [
		{"type": "create_timer", "name": "$$(self.name)_$$(self.idx)_update", "time": "08:01:00", "category": "citizen", "label": "$$self.name"},
	],
	"subsequences": ["daily_update", "begin_work", "end_work", "greet"]
},
{
	"milestone": "daily_update",
	"visible": false,
	"drop": "false",
	"triggers": [{"type": "time_up", "name": "$$(self.name)_$$(self.idx)_update"}],
	"dialogs": [],
	"changes": [
		{"type": "create_timer", "name": "$$(self.name)_$$(self.idx)_update", "time": "00:00:00", "category": "citizen", "label": "$$self.name"},
		{"type": "create_timer", "name": "$$(self.name)_$$(self.idx)_begin_work", "time": "$$self.signin_time", "category": "citizen", "label": "$$self.name"},
		{"type": "create_timer", "name": "$$(self.name)_$$(self.idx)_end_work", "time": "$$self.signout_time", "category": "citizen", "label": "$$self.name"},
	],
	"subsequences": []
},
{
	"milestone": "begin_work",
	"visible": false,
	"drop": "false",
	"triggers": [{"type": "time_up", "name": "$$(self.name)_$$(self.idx)_begin_work"}],
	"dialogs": [],
	"changes": [
		{"type": "npc_navigate", "name": "$$self.name", "destination": "$$self.work_address"}
	],
	"subsequences": ["arrive_work"]
},
{
	"milestone": "arrive_work",
	"visible": false,
	"drop": "true",
	"triggers": [{"type": "npc_arrive", "name": "$$self.name", "address": "$$self.work_address"}],
	"dialogs": [],
	"changes": [
		{"type": "add_option", "name": "$$self.name", "option": "你好"}
	],
	"subsequences": []
},
{
	"milestone": "end_work",
	"visible": false,
	"drop": "false",
	"triggers": [{"type": "time_up", "name": "$$(self.name)_$$(self.idx)_end_work"}],
	"dialogs": [],
	"changes": [
		{"type": "remove_option", "name": "$$self.name", "option": "你好"},
		{"type": "npc_navigate", "name": "$$self.name", "destination": "$$self.home_address"}
	],
	"subsequences": []
},
{
	"milestone": "greet",
	"visible": false,
	"drop": "false",
	"triggers": [{"type": "option_dialog", "name": "$$self.name", "option": "你好"}],
	"dialogs": [
		{"list": [
			{"speaker": "$$self.name", "content": "你好。"},
		]}
	],
	"changes": [],
	"subsequences": []
},
]
