[
{
	"milestone": "game_start",
	"visible": false,
	"triggers": [{"type": "game_start"}],
	"dialogs": [
	],
	"changes": [
		{"type": "add_option", "target": "$$self.name", "option": "你好"}
	],
	"subsequences": [
		"test_dialog"
	]
},
{
	"milestone": "test_dialog",
	"visible": false,
	"drop": "false",
	"triggers": [{"type": "option_dialog", "option": "你好"}],
	"dialogs": [
		{"list": [
			{"content": "你好。"}
		]}
	],
	"changes": [
	],
	"subsequences": []
}
]